/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboadRouteImport } from './routes/dashboad'
import { Route as AlertManagementPageRouteImport } from './routes/alertManagementPage'
import { Route as IndexRouteImport } from './routes/index'

const DashboadRoute = DashboadRouteImport.update({
  id: '/dashboad',
  path: '/dashboad',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertManagementPageRoute = AlertManagementPageRouteImport.update({
  id: '/alertManagementPage',
  path: '/alertManagementPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertManagementPage': typeof AlertManagementPageRoute
  '/dashboad': typeof DashboadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertManagementPage': typeof AlertManagementPageRoute
  '/dashboad': typeof DashboadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertManagementPage': typeof AlertManagementPageRoute
  '/dashboad': typeof DashboadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alertManagementPage' | '/dashboad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alertManagementPage' | '/dashboad'
  id: '__root__' | '/' | '/alertManagementPage' | '/dashboad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertManagementPageRoute: typeof AlertManagementPageRoute
  DashboadRoute: typeof DashboadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboad': {
      id: '/dashboad'
      path: '/dashboad'
      fullPath: '/dashboad'
      preLoaderRoute: typeof DashboadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertManagementPage': {
      id: '/alertManagementPage'
      path: '/alertManagementPage'
      fullPath: '/alertManagementPage'
      preLoaderRoute: typeof AlertManagementPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertManagementPageRoute: AlertManagementPageRoute,
  DashboadRoute: DashboadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
